### ISSUE TITLE
New paper

### ISSUE THREAD

**Issue by 0nhc** [kingchou007/Awesome-Dexterous-Hand#1]
https://ieeexplore.ieee.org/abstract/document/10766612

**Comment by kingchou007** [comment]
[RAL] Q. Wu, H. Wang, J. Zhou, X. Xiong and Y. Lou. (2025) "TARS: Tactile Affordance in Robot Synesthesia for Dexterous Manipulation" - [paper](https://ieeexplore.ieee.org/abstract/document/10766612)
